# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0002_auto_20170607_1525'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='choice',
        #     name='choice_text',
        #     field=models.CharField(default='text', max_length=200),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='choice',
        #     name='question',
        #     field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='leap.Question'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='choice',
        #     name='votes',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name='question',
        #     name='pub_date',
        #     field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='question',
        #     name='question_text',
        #     field=models.CharField(default=django.utils.timezone.now, max_length=200),
        #     preserve_default=False,
        # ),
    ]
