# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0003_auto_20170607_1526'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='choice',
        #     name='choice_text',
        # ),
        # migrations.RemoveField(
        #     model_name='choice',
        #     name='question',
        # ),
        # migrations.RemoveField(
        #     model_name='choice',
        #     name='votes',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='pub_date',
        # ),
        # migrations.RemoveField(
        #     model_name='question',
        #     name='question_text',
        # ),
    ]
