# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0006_auto_20170607_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
