# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0007_auto_20170607_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
